### ISSUE TITLE
itunes backup through my tool

### ISSUE THREAD

**Issue by vivek0626** [stephbu/ITunesSync#1]
hi,
    I want to create iPhone backup through iTunes programatically on window but my problem is the whole backup process perform my tool(not manually), I can not use iTunes application. I can use iTunes services or APIs or SDK or script or command.

please any type of scripts, commands, iTunes API/SDK sample code or link.... 

thanks in advance
Vivek Chauhan

**Comment by stephbu** [comment]
Vivek, this code only uses ITunes and is unaware of the iPhone interfaces.
